[server]
address = "127.0.0.1"
headless = true
runOnSave = true

[browser]
gatherUsageStats = false

[client]
toolbarMode = "viewer"

[theme]
base = "light"
primaryColor = "#07BCF5"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F6F6F5"
textColor = "#222222"
font = "sans-serif"
